export type LanguageMapping = Record<string, string>;

export const typescriptTypeMap: LanguageMapping = {
    "bigInteger"              : "number",
    "boolean"                 : "boolean",
    "date"                    : "string",
    "dateTime"                : "string",
    "decimal"                 : "number",
    "float"                   : "number",
    "integer"                 : "number",
    "json"                    : "any",
    "string"                  : "string",
    "text"                    : "string",
    "time"                    : "string",
    "timestamp"               : "string",
    "binary"                  : "string",
    "uuid"                    : "string",
    "alias"                   : "any",
    "hash"                    : "string",
    "csv"                     : "string[]",
    "geometry"                : "Geometry",
    "geometry.Point"          : "Point",
    "geometry.LineString"     : "LineString",
    "geometry.Polygon"        : "Polygon",
    "geometry.MultiPoint"     : "MultiPoint",
    "geometry.MultiLineString": "MultiLineString",
    "geometry.MultiPolygon"   : "MultiPolygon",
    "unknown"                 : "any",
};

export const rustTypeMap: LanguageMapping = {
    "bigInteger"              : "i64",
    "boolean"                 : "bool",
    "date"                    : "String",
    "dateTime"                : "String",
    "decimal"                 : "f64",
    "float"                   : "f32",
    "integer"                 : "i32",
    "json"                    : "String",
    "string"                  : "String",
    "text"                    : "String",
    "time"                    : "String",
    "timestamp"               : "String",
    "binary"                  : "Vec<u8>",
    "uuid"                    : "String",
    "alias"                   : "String",
    "hash"                    : "String",
    "csv"                     : "Vec<String>",
    "geometry"                : "Geometry",
    "geometry.Point"          : "Point",
    "geometry.LineString"     : "LineString",
    "geometry.Polygon"        : "Polygon",
    "geometry.MultiPoint"     : "MultiPoint",
    "geometry.MultiLineString": "MultiLineString",
    "geometry.MultiPolygon"   : "MultiPolygon",
    "unknown"                 : "String",
};

export const phpTypeMap: LanguageMapping = {
    "bigInteger"              : "int",
    "boolean"                 : "bool",
    "date"                    : "string",
    "dateTime"                : "string",
    "decimal"                 : "float",
    "float"                   : "float",
    "integer"                 : "int",
    "json"                    : "array",
    "string"                  : "string",
    "text"                    : "string",
    "time"                    : "string",
    "timestamp"               : "string",
    "binary"                  : "string",
    "uuid"                    : "string",
    "alias"                   : "mixed",
    "hash"                    : "string",
    "csv"                     : "array",
    "geometry"                : "Geometry",
    "geometry.Point"          : "Point",
    "geometry.LineString"     : "LineString",
    "geometry.Polygon"        : "Polygon",
    "geometry.MultiPoint"     : "MultiPoint",
    "geometry.MultiLineString": "MultiLineString",
    "geometry.MultiPolygon"   : "MultiPolygon",
    "unknown"                 : "mixed",
};

export const csharpTypeMap: LanguageMapping = {
    "bigInteger"              : "long",
    "boolean"                 : "bool",
    "date"                    : "string",
    "dateTime"                : "string",
    "decimal"                 : "decimal",
    "float"                   : "float",
    "integer"                 : "int",
    "json"                    : "string",
    "string"                  : "string",
    "text"                    : "string",
    "time"                    : "string",
    "timestamp"               : "string",
    "binary"                  : "byte[]",
    "uuid"                    : "string",
    "alias"                   : "object",
    "hash"                    : "string",
    "csv"                     : "string[]",
    "geometry"                : "Geometry",
    "geometry.Point"          : "Point",
    "geometry.LineString"     : "LineString",
    "geometry.Polygon"        : "Polygon",
    "geometry.MultiPoint"     : "MultiPoint",
    "geometry.MultiLineString": "MultiLineString",
    "geometry.MultiPolygon"   : "MultiPolygon",
    "unknown"                 : "object",
};

export const javaTypeMap: LanguageMapping = {
    "bigInteger"              : "Long",
    "boolean"                 : "Boolean",
    "date"                    : "String",
    "dateTime"                : "String",
    "decimal"                 : "Double",
    "float"                   : "Float",
    "integer"                 : "Integer",
    "json"                    : "String",
    "string"                  : "String",
    "text"                    : "String",
    "time"                    : "String",
    "timestamp"               : "String",
    "binary"                  : "byte[]",
    "uuid"                    : "String",
    "alias"                   : "Object",
    "hash"                    : "String",
    "csv"                     : "List<String>",
    "geometry"                : "Geometry",
    "geometry.Point"          : "Point",
    "geometry.LineString"     : "LineString",
    "geometry.Polygon"        : "Polygon",
    "geometry.MultiPoint"     : "MultiPoint",
    "geometry.MultiLineString": "MultiLineString",
    "geometry.MultiPolygon"   : "MultiPolygon",
    "unknown"                 : "Object",
};

export const pythonTypeMap: LanguageMapping = {
    "bigInteger"              : "int",
    "boolean"                 : "bool",
    "date"                    : "str",
    "dateTime"                : "str",
    "decimal"                 : "float",
    "float"                   : "float",
    "integer"                 : "int",
    "json"                    : "dict",
    "string"                  : "str",
    "text"                    : "str",
    "time"                    : "str",
    "timestamp"               : "str",
    "binary"                  : "bytes",
    "uuid"                    : "str",
    "alias"                   : "Any",
    "hash"                    : "str",
    "csv"                     : "List[str]",
    "geometry"                : "Geometry",
    "geometry.Point"          : "Point",
    "geometry.LineString"     : "LineString",
    "geometry.Polygon"        : "Polygon",
    "geometry.MultiPoint"     : "MultiPoint",
    "geometry.MultiLineString": "MultiLineString",
    "geometry.MultiPolygon"   : "MultiPolygon",
    "unknown"                 : "Any",
};

export const goTypeMap: LanguageMapping = {
    "bigInteger"              : "int64",
    "boolean"                 : "bool",
    "date"                    : "string",
    "dateTime"                : "string",
    "decimal"                 : "float64",
    "float"                   : "float32",
    "integer"                 : "int32",
    "json"                    : "map[string]interface{}",
    "string"                  : "string",
    "text"                    : "string",
    "time"                    : "string",
    "timestamp"               : "string",
    "binary"                  : "[]byte",
    "uuid"                    : "string",
    "alias"                   : "interface{}",
    "hash"                    : "string",
    "csv"                     : "[]string",
    "geometry"                : "Geometry",
    "geometry.Point"          : "Point",
    "geometry.LineString"     : "LineString",
    "geometry.Polygon"        : "Polygon",
    "geometry.MultiPoint"     : "MultiPoint",
    "geometry.MultiLineString": "MultiLineString",
    "geometry.MultiPolygon"   : "MultiPolygon",
    "unknown"                 : "interface{}",
};

export const cppTypeMap: LanguageMapping = {
    "bigInteger"              : "long long",
    "boolean"                 : "bool",
    "date"                    : "std::string",
    "dateTime"                : "std::string",
    "decimal"                 : "double",
    "float"                   : "float",
    "integer"                 : "int",
    "json"                    : "std::string",
    "string"                  : "std::string",
    "text"                    : "std::string",
    "time"                    : "std::string",
    "timestamp"               : "std::string",
    "binary"                  : "std::vector<unsigned char>",
    "uuid"                    : "std::string",
    "alias"                   : "void*",
    "hash"                    : "std::string",
    "csv"                     : "std::vector<std::string>",
    "geometry"                : "Geometry",
    "geometry.Point"          : "Point",
    "geometry.LineString"     : "LineString",
    "geometry.Polygon"        : "Polygon",
    "geometry.MultiPoint"     : "MultiPoint",
    "geometry.MultiLineString": "MultiLineString",
    "geometry.MultiPolygon"   : "MultiPolygon",
    "unknown"                 : "void*",
};

export const rubyTypeMap: LanguageMapping = {
    "bigInteger"              : "Integer",
    "boolean"                 : "TrueClass/FalseClass",
    "date"                    : "String",
    "dateTime"                : "String",
    "decimal"                 : "Float",
    "float"                   : "Float",
    "integer"                 : "Integer",
    "json"                    : "Hash",
    "string"                  : "String",
    "text"                    : "String",
    "time"                    : "String",
    "timestamp"               : "String",
    "binary"                  : "String",
    "uuid"                    : "String",
    "alias"                   : "Object",
    "hash"                    : "String",
    "csv"                     : "Array",
    "geometry"                : "Geometry",
    "geometry.Point"          : "Point",
    "geometry.LineString"     : "LineString",
    "geometry.Polygon"        : "Polygon",
    "geometry.MultiPoint"     : "MultiPoint",
    "geometry.MultiLineString": "MultiLineString",
    "geometry.MultiPolygon"   : "MultiPolygon",
    "unknown"                 : "Object",
};

export const sqlTypeMap: LanguageMapping = {
    "bigInteger"              : "BIGINT",
    "boolean"                 : "BOOLEAN",
    "date"                    : "DATE",
    "dateTime"                : "DATETIME",
    "decimal"                 : "DECIMAL",
    "float"                   : "FLOAT",
    "integer"                 : "INTEGER",
    "json"                    : "JSON",
    "string"                  : "VARCHAR(255)",
    "text"                    : "TEXT",
    "time"                    : "TIME",
    "timestamp"               : "TIMESTAMP",
    "binary"                  : "BLOB",
    "uuid"                    : "CHAR(36)",
    "alias"                   : "TEXT",
    "hash"                    : "VARCHAR(255)",
    "csv"                     : "TEXT",
    "geometry"                : "GEOMETRY",
    "geometry.Point"          : "POINT",
    "geometry.LineString"     : "LINESTRING",
    "geometry.Polygon"        : "POLYGON",
    "geometry.MultiPoint"     : "MULTIPOINT",
    "geometry.MultiLineString": "MULTILINESTRING",
    "geometry.MultiPolygon"   : "MULTIPOLYGON",
    "unknown"                 : "TEXT",
};

export const kotlinTypeMap: LanguageMapping = {
    "bigInteger"              : "Long",
    "boolean"                 : "Boolean",
    "date"                    : "String",
    "dateTime"                : "String",
    "decimal"                 : "Double",
    "float"                   : "Float",
    "integer"                 : "Int",
    "json"                    : "String",
    "string"                  : "String",
    "text"                    : "String",
    "time"                    : "String",
    "timestamp"               : "String",
    "binary"                  : "ByteArray",
    "uuid"                    : "String",
    "alias"                   : "Any",
    "hash"                    : "String",
    "csv"                     : "List<String>",
    "geometry"                : "Geometry",
    "geometry.Point"          : "Point",
    "geometry.LineString"     : "LineString",
    "geometry.Polygon"        : "Polygon",
    "geometry.MultiPoint"     : "MultiPoint",
    "geometry.MultiLineString": "MultiLineString",
    "geometry.MultiPolygon"   : "MultiPolygon",
    "unknown"                 : "Any",
};

export const graphqlTypeMap: LanguageMapping = {
    "bigInteger"              : "Int",
    "boolean"                 : "Boolean",
    "date"                    : "String",
    "dateTime"                : "String",
    "decimal"                 : "Float",
    "float"                   : "Float",
    "integer"                 : "Int",
    "json"                    : "JSON",
    "string"                  : "String",
    "text"                    : "String",
    "time"                    : "String",
    "timestamp"               : "String",
    "binary"                  : "String",
    "uuid"                    : "String",
    "alias"                   : "JSON",
    "hash"                    : "String",
    "csv"                     : "[String]",
    "geometry"                : "Geometry",
    "geometry.Point"          : "Point",
    "geometry.LineString"     : "LineString",
    "geometry.Polygon"        : "Polygon",
    "geometry.MultiPoint"     : "MultiPoint",
    "geometry.MultiLineString": "MultiLineString",
    "geometry.MultiPolygon"   : "MultiPolygon",
    "unknown"                 : "JSON",
};
